{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: transformers in /home/g22/.local/lib/python3.10/site-packages (4.46.0)\n",
      "Requirement already satisfied: tokenizers<0.21,>=0.20 in /home/g22/.local/lib/python3.10/site-packages (from transformers) (0.20.1)\n",
      "Requirement already satisfied: tqdm>=4.27 in /usr/lib/python3/dist-packages (from transformers) (4.57.0)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in /home/g22/.local/lib/python3.10/site-packages (from transformers) (0.4.5)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.4.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from transformers) (21.3)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/g22/.local/lib/python3.10/site-packages (from transformers) (2.1.2)\n",
      "Requirement already satisfied: filelock in /home/g22/.local/lib/python3.10/site-packages (from transformers) (3.16.1)\n",
      "Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from transformers) (2.25.1)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /home/g22/.local/lib/python3.10/site-packages (from transformers) (0.26.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /home/g22/.local/lib/python3.10/site-packages (from transformers) (2024.9.11)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/g22/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.10.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/g22/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: flash in /home/g22/.local/lib/python3.10/site-packages (1.0.3)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting flash_attn\n",
      "  Downloading flash_attn-2.6.3.tar.gz (2.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.6/2.6 MB\u001b[0m \u001b[31m11.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[20 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m fatal: not a git repository (or any of the parent directories): .git\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m torch.__version__  = 2.5.0+cu124\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m /tmp/pip-install-1451p2nw/flash-attn_4b0b40076673496688fb6df4f9e18365/setup.py:95: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.\n",
      "  \u001b[31m   \u001b[0m   warnings.warn(\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-1451p2nw/flash-attn_4b0b40076673496688fb6df4f9e18365/setup.py\", line 179, in <module>\n",
      "  \u001b[31m   \u001b[0m     CUDAExtension(\n",
      "  \u001b[31m   \u001b[0m   File \"/home/g22/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1078, in CUDAExtension\n",
      "  \u001b[31m   \u001b[0m     library_dirs += library_paths(cuda=True)\n",
      "  \u001b[31m   \u001b[0m   File \"/home/g22/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1209, in library_paths\n",
      "  \u001b[31m   \u001b[0m     if (not os.path.exists(_join_cuda_home(lib_dir)) and\n",
      "  \u001b[31m   \u001b[0m   File \"/home/g22/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 2416, in _join_cuda_home\n",
      "  \u001b[31m   \u001b[0m     raise OSError('CUDA_HOME environment variable is not set. '\n",
      "  \u001b[31m   \u001b[0m OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: timm in /home/g22/.local/lib/python3.10/site-packages (1.0.11)\n",
      "Requirement already satisfied: torch in /home/g22/.local/lib/python3.10/site-packages (from timm) (2.5.0)\n",
      "Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from timm) (5.4.1)\n",
      "Requirement already satisfied: safetensors in /home/g22/.local/lib/python3.10/site-packages (from timm) (0.4.5)\n",
      "Requirement already satisfied: torchvision in /home/g22/.local/lib/python3.10/site-packages (from timm) (0.20.0)\n",
      "Requirement already satisfied: huggingface_hub in /home/g22/.local/lib/python3.10/site-packages (from timm) (0.26.1)\n",
      "Requirement already satisfied: filelock in /home/g22/.local/lib/python3.10/site-packages (from huggingface_hub->timm) (3.16.1)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /usr/lib/python3/dist-packages (from huggingface_hub->timm) (4.57.0)\n",
      "Requirement already satisfied: packaging>=20.9 in /usr/lib/python3/dist-packages (from huggingface_hub->timm) (21.3)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/g22/.local/lib/python3.10/site-packages (from huggingface_hub->timm) (2024.10.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/g22/.local/lib/python3.10/site-packages (from huggingface_hub->timm) (4.12.2)\n",
      "Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from huggingface_hub->timm) (2.25.1)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.4.127)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.4.127)\n",
      "Requirement already satisfied: jinja2 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (3.1.4)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.3.1.170)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (11.6.1.9)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (10.3.5.147)\n",
      "Requirement already satisfied: triton==3.1.0 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (3.1.0)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (11.2.1.3)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.4.127)\n",
      "Requirement already satisfied: sympy==1.13.1 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (1.13.1)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (12.4.5.8)\n",
      "Requirement already satisfied: networkx in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (3.4.2)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (9.1.0.70)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/g22/.local/lib/python3.10/site-packages (from torch->timm) (2.21.5)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/g22/.local/lib/python3.10/site-packages (from sympy==1.13.1->torch->timm) (1.3.0)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/g22/.local/lib/python3.10/site-packages (from torchvision->timm) (11.0.0)\n",
      "Requirement already satisfied: numpy in /home/g22/.local/lib/python3.10/site-packages (from torchvision->timm) (2.1.2)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/g22/.local/lib/python3.10/site-packages (from jinja2->torch->timm) (3.0.2)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: einops in /home/g22/.local/lib/python3.10/site-packages (0.8.0)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: supervision==0.22.0 in /home/g22/.local/lib/python3.10/site-packages (0.22.0)\n",
      "Requirement already satisfied: matplotlib>=3.6.0 in /home/g22/.local/lib/python3.10/site-packages (from supervision==0.22.0) (3.9.2)\n",
      "Requirement already satisfied: pillow>=9.4 in /home/g22/.local/lib/python3.10/site-packages (from supervision==0.22.0) (11.0.0)\n",
      "Requirement already satisfied: numpy>=1.21.2 in /home/g22/.local/lib/python3.10/site-packages (from supervision==0.22.0) (2.1.2)\n",
      "Requirement already satisfied: scipy<2.0.0,>=1.10.0 in /home/g22/.local/lib/python3.10/site-packages (from supervision==0.22.0) (1.14.1)\n",
      "Requirement already satisfied: opencv-python-headless>=4.5.5.64 in /home/g22/.local/lib/python3.10/site-packages (from supervision==0.22.0) (4.10.0.84)\n",
      "Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /home/g22/.local/lib/python3.10/site-packages (from supervision==0.22.0) (0.7.1)\n",
      "Requirement already satisfied: pyyaml>=5.3 in /usr/lib/python3/dist-packages (from supervision==0.22.0) (5.4.1)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.6.0->supervision==0.22.0) (2.4.7)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /home/g22/.local/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision==0.22.0) (2.9.0.post0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/g22/.local/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision==0.22.0) (1.3.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib>=3.6.0->supervision==0.22.0) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /usr/lib/python3/dist-packages (from matplotlib>=3.6.0->supervision==0.22.0) (4.29.1)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.6.0->supervision==0.22.0) (1.3.2)\n",
      "Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from matplotlib>=3.6.0->supervision==0.22.0) (21.3)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6.0->supervision==0.22.0) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install transformers\n",
    "!pip install flash\n",
    "!pip install flash_attn\n",
    "!pip install timm \n",
    "!pip install einops \n",
    "!pip install supervision==0.22.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
